import { Trade } from './types';

const now = Date.now();
const oneDay = 24 * 60 * 60 * 1000;
const oneHour = 60 * 60 * 1000;
const oneMinute = 60 * 1000;

export const MOCK_TRADES: Trade[] = [
  // --- OPEN POSITIONS ---
  {
    id: 'open-1',
    symbol: 'SOL',
    pair: 'SOL/USDC',
    type: 'long',
    entryPrice: 198.50,
    quantity: 50,
    entryTime: now - 2 * oneHour,
    currentPrice: 202.10,
    unrealizedPnl: 180,
    pnlPercent: 1.81,
    orderType: 'market',
    fee: 2.5,
    notes: 'Breakout retest',
    tags: ['Breakout', 'Scalp'],
    status: 'open',
  },
  {
    id: 'open-2',
    symbol: 'BTC',
    pair: 'BTC/USDC',
    type: 'short',
    entryPrice: 44200,
    quantity: 0.5,
    entryTime: now - 5 * oneHour,
    currentPrice: 43900,
    unrealizedPnl: 150,
    pnlPercent: 0.68,
    orderType: 'limit',
    fee: 5.0,
    notes: 'H4 bearish divergence',
    tags: ['Reversal', 'Swing'],
    status: 'open',
  },
  // --- CLOSED TRADES (HISTORY) ---
  {
    id: '1',
    symbol: 'SOL',
    pair: 'SOL/USDC',
    type: 'long',
    entryPrice: 189.5,
    exitPrice: 195.2,
    quantity: 10,
    pnl: 57,
    pnlPercent: 2.99,
    entryTime: now - 2 * oneDay,
    exitTime: now - 2 * oneDay + 4 * oneHour,
    durationMinutes: 240,
    orderType: 'market',
    fee: 0.5,
    notes: 'Clean breakout above resistance',
    tags: ['Breakout'],
    status: 'closed',
  },
  {
    id: '2',
    symbol: 'SOL',
    pair: 'SOL/USDC',
    type: 'short',
    entryPrice: 192.8,
    exitPrice: 188.5,
    quantity: 15,
    pnl: 64.5,
    pnlPercent: 2.23,
    entryTime: now - 1.8 * oneDay,
    exitTime: now - 1.8 * oneDay + 3 * oneHour,
    durationMinutes: 180,
    orderType: 'limit',
    fee: 0.75,
    notes: 'Rejection at supply zone',
    tags: ['Reversal'],
    status: 'closed',
  },
  {
    id: '3',
    symbol: 'BTC',
    pair: 'BTC/USDC',
    type: 'long',
    entryPrice: 42150,
    exitPrice: 41920,
    quantity: 0.05,
    pnl: -11.5,
    pnlPercent: -0.55,
    entryTime: now - 1.5 * oneDay,
    exitTime: now - 1.5 * oneDay + 90 * oneMinute,
    durationMinutes: 90,
    orderType: 'market',
    fee: 0.35,
    notes: 'Stop loss hit - false breakout',
    tags: ['Stop Loss'],
    status: 'closed',
  },
  {
    id: '4',
    symbol: 'ETH',
    pair: 'ETH/USDC',
    type: 'long',
    entryPrice: 2340.5,
    exitPrice: 2385.3,
    quantity: 2,
    pnl: 89.6,
    pnlPercent: 1.92,
    entryTime: now - 1.2 * oneDay,
    exitTime: now - 1.2 * oneDay + 5 * oneHour,
    durationMinutes: 300,
    orderType: 'limit',
    fee: 0.6,
    notes: 'Textbook trend continuation',
    tags: ['Trend Following'],
    status: 'closed',
  },
  {
    id: '5',
    symbol: 'SOL',
    pair: 'SOL/USDC',
    type: 'short',
    entryPrice: 194.2,
    exitPrice: 197.5,
    quantity: 20,
    pnl: -66,
    pnlPercent: -1.71,
    entryTime: now - 0.9 * oneDay,
    exitTime: now - 0.9 * oneDay + 2 * oneHour,
    durationMinutes: 120,
    orderType: 'market',
    fee: 1.0,
    notes: 'Caught in momentum - emotional exit',
    tags: ['FOMO'],
    status: 'closed',
  },
  {
    id: '6',
    symbol: 'BTC',
    pair: 'BTC/USDC',
    type: 'long',
    entryPrice: 41850,
    exitPrice: 43120,
    quantity: 0.08,
    pnl: 101.6,
    pnlPercent: 3.04,
    entryTime: now - 0.7 * oneDay,
    exitTime: now - 0.7 * oneDay + 8 * oneHour,
    durationMinutes: 480,
    orderType: 'limit',
    fee: 0.5,
    notes: 'Good patience, let winners run',
    tags: ['Trend Following'],
    status: 'closed',
  },
  {
    id: '7',
    symbol: 'ETH',
    pair: 'ETH/USDC',
    type: 'short',
    entryPrice: 2400,
    exitPrice: 2365.8,
    quantity: 3,
    pnl: 102.6,
    pnlPercent: 1.42,
    entryTime: now - 0.5 * oneDay,
    exitTime: now - 0.5 * oneDay + 2.5 * oneHour,
    durationMinutes: 150,
    orderType: 'market',
    fee: 0.8,
    notes: 'Nice pullback sell opportunity',
    tags: ['Pullback'],
    status: 'closed',
  },
  {
    id: '8',
    symbol: 'SOL',
    pair: 'SOL/USDC',
    type: 'long',
    entryPrice: 191.5,
    exitPrice: 193.8,
    quantity: 12,
    pnl: 27.6,
    pnlPercent: 1.2,
    entryTime: now - 0.3 * oneDay,
    exitTime: now - 0.3 * oneDay + 1 * oneHour,
    durationMinutes: 60,
    orderType: 'limit',
    fee: 0.4,
    notes: 'Scalp trade - quick profit',
    tags: ['Scalp'],
    status: 'closed',
  },
  {
    id: '9',
    symbol: 'BTC',
    pair: 'BTC/USDC',
    type: 'short',
    entryPrice: 43000,
    exitPrice: 42500,
    quantity: 0.1,
    pnl: 50,
    pnlPercent: 1.16,
    entryTime: now - 0.15 * oneDay,
    exitTime: now - 0.15 * oneDay + 3 * oneHour,
    durationMinutes: 180,
    orderType: 'market',
    fee: 0.6,
    notes: 'Distribution pattern confirmed',
    tags: ['Pattern'],
    status: 'closed',
  },
  {
    id: '10',
    symbol: 'ETH',
    pair: 'ETH/USDC',
    type: 'long',
    entryPrice: 2370,
    exitPrice: 2349.5,
    quantity: 1.5,
    pnl: -30.75,
    pnlPercent: -1.15,
    entryTime: now - 0.08 * oneDay,
    exitTime: now - 0.08 * oneDay + 45 * oneMinute,
    durationMinutes: 45,
    orderType: 'stop-loss',
    fee: 0.3,
    notes: 'Wrong timing on the entry',
    tags: ['Mistake'],
    status: 'closed',
  },
  {
    id: '11',
    symbol: 'SOL',
    pair: 'SOL/USDC',
    type: 'short',
    entryPrice: 195.0,
    exitPrice: 193.2,
    quantity: 18,
    pnl: 32.4,
    pnlPercent: 0.92,
    entryTime: now - 0.04 * oneDay,
    exitTime: now - 0.04 * oneDay + 2 * oneHour,
    durationMinutes: 120,
    orderType: 'limit',
    fee: 0.65,
    notes: 'Solid risk/reward ratio',
    tags: ['Swing'],
    status: 'closed',
  },
  {
    id: '12',
    symbol: 'BTC',
    pair: 'BTC/USDC',
    type: 'long',
    entryPrice: 42400,
    exitPrice: 42850,
    quantity: 0.06,
    pnl: 27,
    pnlPercent: 1.06,
    entryTime: now - 0.02 * oneDay,
    exitTime: now - 0.01 * oneDay,
    durationMinutes: 30,
    orderType: 'market',
    fee: 0.25,
    notes: 'Today - quick entry and exit',
    tags: ['Scalp'],
    status: 'closed',
  },
];

export const MOCK_SYMBOLS = ['SOL', 'BTC', 'ETH'];
export const MOCK_PAIRS = ['SOL/USDC', 'BTC/USDC', 'ETH/USDC'];
